# typed: false
# frozen_string_literal: true

# Generated by scripts/update_homebrew_formula.sh for v0.5.0.
# release.yml re-runs that script after each tagged release.
# Do not hand-edit sha256 values.
#
# Install (Homebrew 6+ requires tap trust):
#   brew tap whycorporation/whycodes https://github.com/whycorporation/whycodes
#   brew install whycorporation/whycodes/whycodes
#
# If already tapped:
#   brew trust --formula whycorporation/whycodes/whycodes
#   brew install whycodes
#
# Source tip (needs a Rust toolchain):
#   brew install --HEAD whycorporation/whycodes/whycodes

class Whycodes < Formula
  desc "Terminal coding agent written in Rust"
  homepage "https://why.codes"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/whycorporation/whycodes/releases/download/v0.5.0/whycodes-aarch64-apple-darwin.tar.gz"
      sha256 "ff140d88ca05dad48dfe924674df948dc2703499a83144e2fbda5588759332e2"
    end

    on_intel do
      url "https://github.com/whycorporation/whycodes/releases/download/v0.5.0/whycodes-x86_64-apple-darwin.tar.gz"
      sha256 "7b80bfa42869605e5af909361da5f5670f9a01dbe5010fdb066b55b013c6a6aa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/whycorporation/whycodes/releases/download/v0.5.0/whycodes-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "dccd785df14075707bbf010b7e79d4560d4d25250c5d219125c81a1d73411a02"
    end
  end

  head do
    url "https://github.com/whycorporation/whycodes.git", branch: "main"
    depends_on "rust" => :build
  end

  livecheck do
    url "https://github.com/whycorporation/whycodes/releases/latest"
    strategy :github_latest
  end

  def install
    if build.head?
      system "cargo", "install", "--locked", "--features", "bundled-sqlite", *std_cargo_args(path: "crates/cli")
    elsif File.exist?("whycodes")
      bin.install "whycodes"
    elsif File.exist?("whycode")
      # v0.1.0 archives still ship the pre-rebrand binary name.
      bin.install "whycode" => "whycodes"
    else
      odie "archive did not contain a whycodes binary"
    end
    generate_completions_from_executable(bin/"whycodes", "completions")
  end

  def caveats
    <<~EOS
      The binary is unsigned, so macOS Gatekeeper may warn on first run.
      Update with `brew upgrade whycodes` rather than `whycodes upgrade`.
    EOS
  end

  test do
    assert_match "whycodes", shell_output("#{bin}/whycodes --version")
    assert_match "whycodes", shell_output("#{bin}/whycodes completions bash")
  end
end
