# typed: false
# frozen_string_literal: true

# Generated by scripts/update_homebrew_formula.sh for v0.3.0.
# release.yml re-runs that script after each tagged release.
# Do not hand-edit sha256 values.
#
# Install (Homebrew 6+ requires tap trust):
#   brew tap whycorporation/whycodes https://github.com/whycorporation/whycodes
#   brew install whycorporation/whycodes/whycodes
#
# If already tapped:
#   brew trust --formula whycorporation/whycodes/whycodes
#   brew install whycodes
#
# Source tip (needs a Rust toolchain):
#   brew install --HEAD whycorporation/whycodes/whycodes

class Whycodes < Formula
  desc "Terminal coding agent written in Rust"
  homepage "https://why.codes"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/whycorporation/whycodes/releases/download/v0.3.0/whycodes-aarch64-apple-darwin.tar.gz"
      sha256 "3a43713815adf9c302ed2905cc7140c37bd4423fcf945dc50ca06da7ba9aceac"
    end

    on_intel do
      url "https://github.com/whycorporation/whycodes/releases/download/v0.3.0/whycodes-x86_64-apple-darwin.tar.gz"
      sha256 "5796b7c158d1e7b0cdb72ed25d13c06c1a0e4b2006d087dba944a41980de47bf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/whycorporation/whycodes/releases/download/v0.3.0/whycodes-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "07bffafea6393ef395770892ddd284a29208ea88aa12b289ea4f220e15917343"
    end
  end

  head do
    url "https://github.com/whycorporation/whycodes.git", branch: "main"
    depends_on "rust" => :build
  end

  livecheck do
    url "https://github.com/whycorporation/whycodes/releases/latest"
    strategy :github_latest
  end

  def install
    if build.head?
      system "cargo", "install", "--locked", *std_cargo_args(path: "crates/cli")
    elsif File.exist?("whycodes")
      bin.install "whycodes"
    elsif File.exist?("whycode")
      # v0.1.0 archives still ship the pre-rebrand binary name.
      bin.install "whycode" => "whycodes"
    else
      odie "archive did not contain a whycodes binary"
    end
    generate_completions_from_executable(bin/"whycodes", "completions")
  end

  def caveats
    <<~EOS
      The binary is unsigned, so macOS Gatekeeper may warn on first run.
      Update with `brew upgrade whycodes` rather than `whycodes upgrade`.
    EOS
  end

  test do
    assert_match "whycodes", shell_output("#{bin}/whycodes --version")
    assert_match "whycodes", shell_output("#{bin}/whycodes completions bash")
  end
end
