# typed: false
# frozen_string_literal: true

# Generated by scripts/update_homebrew_formula.sh for v0.6.6.
# release.yml re-runs that script after each tagged release.
# Do not hand-edit sha256 values.
#
# Install (Homebrew 6+ requires tap trust):
#   brew tap whycorporation/whycodes https://github.com/whycorporation/whycodes
#   brew install whycorporation/whycodes/whycodes
#
# If already tapped:
#   brew trust --formula whycorporation/whycodes/whycodes
#   brew install whycodes
#
# Source tip (needs a Rust toolchain):
#   brew install --HEAD whycorporation/whycodes/whycodes

class Whycodes < Formula
  desc "Terminal coding agent written in Rust"
  homepage "https://why.codes"
  version "0.6.6"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/whycorporation/whycodes/releases/download/v0.6.6/whycodes-aarch64-apple-darwin.tar.gz"
      sha256 "98770142c70fdeab56f8465a4aa18cf1d8d078a29daea9ccff58d6089ff88ecc"
    end

    on_intel do
      url "https://github.com/whycorporation/whycodes/releases/download/v0.6.6/whycodes-x86_64-apple-darwin.tar.gz"
      sha256 "3409ce8f1e1f5be5f636cac157796f0f7f0d5254f706e24274de1f27789ab00f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/whycorporation/whycodes/releases/download/v0.6.6/whycodes-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "3afb023fa221a29054cbdbdca9854002bcacd1c099d7a838858b9dbcd80ad6a9"
    end
  end

  head do
    url "https://github.com/whycorporation/whycodes.git", branch: "main"
    depends_on "rust" => :build
  end

  livecheck do
    url "https://github.com/whycorporation/whycodes/releases/latest"
    strategy :github_latest
  end

  def install
    if build.head?
      system "cargo", "install", "--locked", "--features", "bundled-sqlite", *std_cargo_args(path: "crates/cli")
    elsif File.exist?("whycodes")
      bin.install "whycodes"
    elsif File.exist?("whycode")
      # v0.1.0 archives still ship the pre-rebrand binary name.
      bin.install "whycode" => "whycodes"
    else
      odie "archive did not contain a whycodes binary"
    end
    generate_completions_from_executable(bin/"whycodes", "completions")
  end

  def caveats
    <<~EOS
      The binary is unsigned, so macOS Gatekeeper may warn on first run.
      Update with `brew upgrade whycodes` rather than `whycodes upgrade`.
    EOS
  end

  test do
    assert_match "whycodes", shell_output("#{bin}/whycodes --version")
    assert_match "whycodes", shell_output("#{bin}/whycodes completions bash")
  end
end
