#!/usr/bin/env sh
# Update Formula/whycode.rb for a published GitHub release.
#
# Partial package-manager support: after `release.yml` attaches binaries and
# SHA256SUMS, this rewrites the formula as a prebuilt-binary install (macOS +
# Linux), matching the artifact names from `.github/workflows/release.yml`.
#
# Usage:
#   scripts/update_homebrew_formula.sh v0.1.0
#   scripts/update_homebrew_formula.sh 0.1.0          # leading v optional
#   WHYCODE_REPO=owner/repo scripts/update_homebrew_formula.sh v0.1.0
#
# Requires: curl. Does not commit or push — review the diff, then commit.

set -eu

REPO="${WHYCODE_REPO:-whycorporation/whycode}"
ROOT="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
FORMULA="$ROOT/Formula/whycode.rb"

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "$1 is required"; }

need curl

raw_tag="${1:-}"
[ -n "$raw_tag" ] || die "usage: $0 <version|vX.Y.Z>"

case "$raw_tag" in
    v*) tag="$raw_tag"; version="${raw_tag#v}" ;;
    *)  tag="v$raw_tag"; version="$raw_tag" ;;
esac

base="https://github.com/${REPO}/releases/download/${tag}"
sums_url="${base}/SHA256SUMS"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

printf 'Fetching %s\n' "$sums_url"
curl -fsSL "$sums_url" -o "$tmp" \
    || die "could not download SHA256SUMS for ${tag} (has the release been published?)"

digest_for() {
    # SHA256SUMS lines: "<hex>  <filename>" or "<hex> *<filename>"
    name="$1"
    dig="$(grep -E "[[:space:]](\\*)?${name}\$" "$tmp" | awk '{print $1}' | head -n1)"
    [ -n "$dig" ] || die "$name is not listed in SHA256SUMS"
    printf '%s' "$dig"
}

# Artifact names must match release.yml + install.sh / upgrade.rs.
linux_x64="whycode-x86_64-unknown-linux-gnu.tar.gz"
mac_arm="whycode-aarch64-apple-darwin.tar.gz"
mac_x64="whycode-x86_64-apple-darwin.tar.gz"

sha_linux_x64="$(digest_for "$linux_x64")"
sha_mac_arm="$(digest_for "$mac_arm")"
sha_mac_x64="$(digest_for "$mac_x64")"

printf 'Writing binary formula for %s\n' "$tag"

cat > "$FORMULA" <<EOF
# typed: false
# frozen_string_literal: true

# Generated by scripts/update_homebrew_formula.sh for ${tag}.
# Re-run that script after each release; do not hand-edit sha256 values.
#
# Install:
#   brew tap whycorporation/whycode https://github.com/${REPO}
#   brew install whycode
#
# Source tip:
#   brew install --HEAD whycode

class Whycode < Formula
  desc "Terminal coding agent written in Rust"
  homepage "https://github.com/${REPO}"
  version "${version}"
  license "MIT"
  head "https://github.com/${REPO}.git", branch: "main"

  on_macos do
    on_arm do
      url "${base}/${mac_arm}"
      sha256 "${sha_mac_arm}"

      def install
        bin.install "whycode"
      end
    end

    on_intel do
      url "${base}/${mac_x64}"
      sha256 "${sha_mac_x64}"

      def install
        bin.install "whycode"
      end
    end
  end

  on_linux do
    on_intel do
      url "${base}/${linux_x64}"
      sha256 "${sha_linux_x64}"

      def install
        bin.install "whycode"
      end
    end
  end

  test do
    assert_match "whycode", shell_output("#{bin}/whycode --version")
  end
end
EOF

printf 'Updated %s\n' "$FORMULA"
printf 'Next: review the diff, commit Formula/whycode.rb, push.\n'
printf 'Users: brew update && brew upgrade whycode  (or reinstall)\n'
