#!/usr/bin/env sh
# Update Formula/whycodes.rb for a published GitHub release.
#
# After `release.yml` attaches binaries and SHA256SUMS, this rewrites the
# formula as a prebuilt-binary install (macOS + Linux x86_64). Artifact names
# must match `.github/workflows/release.yml`, `scripts/install.sh`, and
# `crates/cli/src/upgrade.rs`.
#
# `release.yml` runs this after every tagged publish and commits the result
# to main. Manual use is for backfill or local review:
#
#   scripts/update_homebrew_formula.sh v0.1.0
#   scripts/update_homebrew_formula.sh 0.1.0          # leading v optional
#   WHYCODES_REPO=owner/repo scripts/update_homebrew_formula.sh v0.1.0
#   WHYCODES_SHA256SUMS=/path/to/SHA256SUMS scripts/update_homebrew_formula.sh v0.1.0
#
# Requires: curl. Uses `gh` when available (private releases). Does not
# commit — the workflow (or a reviewer) does that.

set -eu

REPO="${WHYCODES_REPO:-whycorporation/whycodes}"
ROOT="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
FORMULA="${WHYCODES_FORMULA:-$ROOT/Formula/whycodes.rb}"
TOKEN="${GITHUB_TOKEN:-${GH_TOKEN:-}}"

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

raw_tag="${1:-}"
[ -n "$raw_tag" ] || die "usage: $0 <version|vX.Y.Z>"

case "$raw_tag" in
    v*) tag="$raw_tag"; version="${raw_tag#v}" ;;
    *)  tag="v$raw_tag"; version="$raw_tag" ;;
esac

base="https://github.com/${REPO}/releases/download/${tag}"
sums_url="${base}/SHA256SUMS"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
sums="$tmp/SHA256SUMS"

fetch_sums() {
    if [ -n "${WHYCODES_SHA256SUMS:-}" ]; then
        [ -f "$WHYCODES_SHA256SUMS" ] || die "WHYCODES_SHA256SUMS is not a file: $WHYCODES_SHA256SUMS"
        cp "$WHYCODES_SHA256SUMS" "$sums"
        return 0
    fi

    if command -v gh >/dev/null 2>&1; then
        if [ -n "$TOKEN" ]; then
            GH_TOKEN="$TOKEN" gh release download "$tag" \
                --repo "$REPO" --pattern SHA256SUMS --output "$sums" && return 0
        elif gh auth status >/dev/null 2>&1; then
            gh release download "$tag" \
                --repo "$REPO" --pattern SHA256SUMS --output "$sums" && return 0
        fi
    fi

    if [ -n "$TOKEN" ]; then
        curl -fsSL -H "Authorization: Bearer ${TOKEN}" "$sums_url" -o "$sums" && return 0
    fi

    curl -fsSL "$sums_url" -o "$sums" \
        || die "could not download SHA256SUMS for ${tag} (has the release been published?)"
}

printf 'Fetching SHA256SUMS for %s\n' "$tag"
fetch_sums

digest_for() {
    # SHA256SUMS lines: "<hex>  <filename>" or "<hex> *<filename>"
    name="$1"
    dig="$(grep -E "[[:space:]](\\*)?${name}\$" "$sums" | awk '{print $1}' | head -n1)"
    [ -n "$dig" ] || die "$name is not listed in SHA256SUMS"
    printf '%s' "$dig"
}

# Artifact names must match release.yml + install.sh / upgrade.rs.
linux_x64="whycodes-x86_64-unknown-linux-gnu.tar.gz"
mac_arm="whycodes-aarch64-apple-darwin.tar.gz"
mac_x64="whycodes-x86_64-apple-darwin.tar.gz"

sha_linux_x64="$(digest_for "$linux_x64")"
sha_mac_arm="$(digest_for "$mac_arm")"
sha_mac_x64="$(digest_for "$mac_x64")"

printf 'Writing binary formula for %s\n' "$tag"

mkdir -p "$(dirname "$FORMULA")"
cat > "$FORMULA" <<EOF
# typed: false
# frozen_string_literal: true

# Generated by scripts/update_homebrew_formula.sh for ${tag}.
# release.yml re-runs that script after each tagged release.
# Do not hand-edit sha256 values.
#
# Install:
#   brew tap whycorporation/whycodes https://github.com/${REPO}
#   brew install whycodes
#
# Source tip (needs a Rust toolchain):
#   brew install --HEAD whycodes

class Whycodes < Formula
  desc "Terminal coding agent written in Rust"
  homepage "https://why.codes"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/${mac_arm}"
      sha256 "${sha_mac_arm}"
    end

    on_intel do
      url "${base}/${mac_x64}"
      sha256 "${sha_mac_x64}"
    end
  end

  on_linux do
    on_intel do
      url "${base}/${linux_x64}"
      sha256 "${sha_linux_x64}"
    end
  end

  head do
    url "https://github.com/${REPO}.git", branch: "main"
    depends_on "rust" => :build
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args(path: "crates/cli")
    else
      bin.install "whycodes"
    end
  end

  test do
    assert_match "whycodes", shell_output("#{bin}/whycodes --version")
  end
end
EOF

printf 'Updated %s\n' "$FORMULA"
printf 'Next: review the diff (CI commits this on release).\n'
printf 'Users: brew update && brew upgrade whycodes  (or reinstall)\n'
